### ISSUE TITLE
Kopiowanie przedmiotów.

### ISSUE THREAD

**Issue by KrejzolekPRO** [SocketByte/OpenGUI#3]
Mój kod: https://pastebin.com/fAuQ4Fip
Na czym polega kopiowanie? Mam sobie w inventory jakieś przedmioty (np. 64 ziemi), wpisuje komendę /kick <mój nick> - otwiera się GUI do potwierdzenia, zamykam je, wyrzucam 64 ziemi, znowu wpisuje tą samą komendę i na slocie x (slot, z którego wyrzuciłem ziemie) pojawia się 64 ziemi (przedmiot, który wyrzuciłem), podnoszę wcześniej wyrzucony przedmiot i mam dwa identyczne. Pozdrawiam :)

**Comment by SocketByte** [comment]
Jesteś pewny że to problem mojego API?
Nie jestem w stanie zreprodukować problemu, poza tym to ma mały sens, albowiem nie ingeruje w inventory gracza. Upewnij się że to wina mojego API.

**Comment by KrejzolekPRO** [comment]
Odpaliłem ten sam serwer po jakimś czasie i ten "bug/błąd" nie występuje, dziwne i to bardzo. Najwyraźniej nie był to błąd Twojego API :)
